# Pull Request just run affected
name: PR Affected CI

on:
  pull_request:
    branches:
      - master
      - develop
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Fetch current master to compare
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn affected:build --base=origin/master
        env:
          CI: true

      - name: Test
        run: yarn affected:lint --base=origin/master
        env:
          CI: true

      - name: Build
        run: yarn affected:lint --base=origin/master
        env:
          CI: true
