name: Merge Master

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
        env:
          CI: true
      - name: Lint
        run: yarn nx run-many --target=lint --all
        env:
          CI: true
      - name: Test
        run: yarn nx run-many --target=test --all --ci --coverage --maxWorkers=2
        env:
          CI: true

