name: PR workflow

on:
  pull_request:
    branches:
      - master
      - develop
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x, 12.x, 10.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn affected:lint -- --base="origin/master"
        env:
          CI: true

      - name: Test
        run: affected:test -- --base="origin/master"
        env:
          CI: true

